import {
  boolean,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  varchar
} from "drizzle-orm/pg-core";

const timestamps = { createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() };

export const appMode = pgEnum("app_mode", ["fixture", "live"]);
export const customerType = pgEnum("customer_type", ["individual", "business"]);
export const obligationKind = pgEnum("obligation_kind", ["purchase", "invoice"]);
export const obligationStatus = pgEnum("obligation_status", ["open", "partially_paid", "paid", "cancelled", "review_required"]);
export const caseState = pgEnum("case_state", ["detected", "investigating", "proposed", "awaiting_approval", "contacted", "recovered", "paused", "escalated", "closed"]);
export const workflowType = pgEnum("workflow_type", ["failed_purchase", "invoice_resolution", "shared_incident"]);
export const blockerCategory = pgEnum("blocker_category", ["payment_failed", "missing_document", "dispute", "promise_to_pay", "partial_payment", "inability_to_pay", "no_response", "incident", "opted_out"]);
export const incidentConfirmation = pgEnum("incident_confirmation", ["confirmed", "inferred", "simulated"]);
export const incidentStatus = pgEnum("incident_status", ["active", "resolved"]);
export const actorType = pgEnum("actor_type", ["system", "agent", "merchant", "customer", "connector"]);

export const merchants = pgTable("merchants", { id: uuid("id").defaultRandom().primaryKey(), name: text("name").notNull(), mode: appMode("mode").notNull(), timezone: text("timezone").notNull(), defaultCurrency: varchar("default_currency", { length: 3 }).notNull(), agentProvider: text("agent_provider").notNull().default("fixture"), evidenceProvider: text("evidence_provider").notNull().default("fixture"), paymentProvider: text("payment_provider").notNull().default("fixture"), storageProvider: text("storage_provider").notNull().default("postgres"), ...timestamps });
export const customers = pgTable("customers", { id: uuid("id").defaultRandom().primaryKey(), merchantId: uuid("merchant_id").notNull().references(() => merchants.id), type: customerType("type").notNull(), displayName: text("display_name").notNull(), email: text("email").notNull(), company: text("company"), externalRefs: jsonb("external_refs").$type<Record<string, string>>().notNull().default({}), ...timestamps }, (table) => ({ merchantEmailIdx: uniqueIndex("customers_merchant_email_idx").on(table.merchantId, table.email) }));
export const obligations = pgTable("obligations", { id: uuid("id").defaultRandom().primaryKey(), merchantId: uuid("merchant_id").notNull().references(() => merchants.id), customerId: uuid("customer_id").notNull().references(() => customers.id), kind: obligationKind("kind").notNull(), amountDue: integer("amount_due").notNull(), amountPaid: integer("amount_paid").notNull().default(0), currency: varchar("currency", { length: 3 }).notNull(), orderRef: text("order_ref"), cartRef: text("cart_ref"), invoiceRef: text("invoice_ref"), status: obligationStatus("status").notNull().default("open"), dueAt: timestamp("due_at", { withTimezone: true }), ...timestamps }, (table) => ({ orderIdx: uniqueIndex("obligations_merchant_order_idx").on(table.merchantId, table.orderRef), invoiceIdx: uniqueIndex("obligations_merchant_invoice_idx").on(table.merchantId, table.invoiceRef) }));
export const recoveryCases = pgTable("recovery_cases", { id: uuid("id").defaultRandom().primaryKey(), merchantId: uuid("merchant_id").notNull().references(() => merchants.id), customerId: uuid("customer_id").notNull().references(() => customers.id), obligationId: uuid("obligation_id").notNull().references(() => obligations.id), workflow: workflowType("workflow").notNull(), state: caseState("state").notNull(), priority: varchar("priority", { length: 12 }).notNull(), blocker: blockerCategory("blocker").notNull(), confidence: integer("confidence_bps").notNull(), reason: text("reason").notNull(), nextAction: text("next_action").notNull(), pauseReason: text("pause_reason"), pauseUntil: timestamp("pause_until", { withTimezone: true }), assignedIncidentId: uuid("assigned_incident_id"), lastAgentInputHash: text("last_agent_input_hash"), lastAgentRunId: uuid("last_agent_run_id"), version: integer("version").notNull().default(1), ...timestamps });
export const signals = pgTable("signals", { id: uuid("id").defaultRandom().primaryKey(), merchantId: uuid("merchant_id").notNull().references(() => merchants.id), type: text("type").notNull(), source: text("source").notNull(), externalId: text("external_id").notNull(), normalizedPayload: jsonb("normalized_payload").$type<Record<string, unknown>>().notNull(), occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(), correlationStatus: text("correlation_status").notNull(), obligationId: uuid("obligation_id").references(() => obligations.id), caseId: uuid("case_id").references(() => recoveryCases.id), ...timestamps }, (table) => ({ providerExternalIdx: uniqueIndex("signals_merchant_source_external_idx").on(table.merchantId, table.source, table.externalId) }));
export const paymentAttempts = pgTable("payment_attempts", { id: uuid("id").defaultRandom().primaryKey(), merchantId: uuid("merchant_id").notNull().references(() => merchants.id), obligationId: uuid("obligation_id").notNull().references(() => obligations.id), razorpayPaymentId: text("razorpay_payment_id").notNull(), amount: integer("amount").notNull(), method: text("method").notNull(), status: text("status").notNull(), errorCode: text("error_code"), errorDescription: text("error_description"), errorSource: text("error_source"), errorStep: text("error_step"), ...timestamps }, (table) => ({ externalIdx: uniqueIndex("payment_attempts_merchant_rzp_idx").on(table.merchantId, table.razorpayPaymentId) }));
export const paymentLinks = pgTable("payment_links", { id: uuid("id").defaultRandom().primaryKey(), merchantId: uuid("merchant_id").notNull().references(() => merchants.id), obligationId: uuid("obligation_id").notNull().references(() => obligations.id), razorpayLinkId: text("razorpay_link_id").notNull(), referenceId: text("reference_id").notNull(), amount: integer("amount").notNull(), amountPaid: integer("amount_paid").notNull().default(0), status: text("status").notNull(), url: text("url").notNull(), publicToken: text("public_token").notNull(), acceptPartial: boolean("accept_partial").notNull().default(true), expiresAt: timestamp("expires_at", { withTimezone: true }), ...timestamps }, (table) => ({ rzpIdx: uniqueIndex("payment_links_merchant_rzp_idx").on(table.merchantId, table.razorpayLinkId), publicIdx: uniqueIndex("payment_links_public_token_idx").on(table.publicToken), obligationIdx: uniqueIndex("payment_links_active_obligation_idx").on(table.merchantId, table.obligationId) }));
export const payments = pgTable("payments", { id: uuid("id").defaultRandom().primaryKey(), merchantId: uuid("merchant_id").notNull().references(() => merchants.id), obligationId: uuid("obligation_id").notNull().references(() => obligations.id), paymentLinkId: uuid("payment_link_id").references(() => paymentLinks.id), razorpayPaymentId: text("razorpay_payment_id").notNull(), amount: integer("amount").notNull(), verified: boolean("verified").notNull().default(false), capturedAt: timestamp("captured_at", { withTimezone: true }), provider: text("provider").notNull(), webhookEventId: text("webhook_event_id"), ...timestamps }, (table) => ({ externalIdx: uniqueIndex("payments_merchant_rzp_idx").on(table.merchantId, table.razorpayPaymentId), webhookIdx: uniqueIndex("payments_merchant_webhook_idx").on(table.merchantId, table.webhookEventId) }));
export const invoices = pgTable("invoices", { id: uuid("id").defaultRandom().primaryKey(), merchantId: uuid("merchant_id").notNull().references(() => merchants.id), obligationId: uuid("obligation_id").notNull().references(() => obligations.id), invoiceNumber: text("invoice_number").notNull(), issueDate: timestamp("issue_date", { withTimezone: true }).notNull(), dueDate: timestamp("due_date", { withTimezone: true }).notNull(), documentId: uuid("document_id"), ...timestamps }, (table) => ({ invoiceIdx: uniqueIndex("invoices_merchant_number_idx").on(table.merchantId, table.invoiceNumber) }));
export const messages = pgTable("messages", { id: uuid("id").defaultRandom().primaryKey(), merchantId: uuid("merchant_id").notNull().references(() => merchants.id), caseId: uuid("case_id").references(() => recoveryCases.id), obligationId: uuid("obligation_id").references(() => obligations.id), direction: text("direction").notNull(), channel: text("channel").notNull(), providerId: text("provider_id").notNull(), threadId: text("thread_id"), subject: text("subject").notNull(), body: text("body").notNull(), participants: jsonb("participants").$type<string[]>().notNull(), fromAddress: text("from_address"), toAddresses: jsonb("to_addresses").$type<string[]>(), providerMode: text("provider_mode"), providerUrl: text("provider_url"), sentAt: timestamp("sent_at", { withTimezone: true }), receivedAt: timestamp("received_at", { withTimezone: true }), ...timestamps });
export const documents = pgTable("documents", { id: uuid("id").defaultRandom().primaryKey(), merchantId: uuid("merchant_id").notNull().references(() => merchants.id), customerId: uuid("customer_id").references(() => customers.id), obligationId: uuid("obligation_id").references(() => obligations.id), providerId: text("provider_id").notNull(), name: text("name").notNull(), mimeType: text("mime_type").notNull(), extractedText: text("extracted_text").notNull(), sourceUrl: text("source_url").notNull(), checksum: text("checksum").notNull(), permission: text("permission").notNull(), providerMode: text("provider_mode"), matchReason: text("match_reason"), ...timestamps });
export const incidents = pgTable("incidents", { id: uuid("id").defaultRandom().primaryKey(), merchantId: uuid("merchant_id").notNull().references(() => merchants.id), source: text("source").notNull(), method: text("method").notNull(), provider: text("provider").notNull(), instrument: text("instrument").notNull(), severity: varchar("severity", { length: 12 }).notNull(), confirmation: incidentConfirmation("confirmation").notNull(), status: incidentStatus("status").notNull(), startedAt: timestamp("started_at", { withTimezone: true }).notNull(), resolvedAt: timestamp("resolved_at", { withTimezone: true }), summary: text("summary").notNull(), evidence: jsonb("evidence").$type<string[]>().notNull(), ...timestamps });
export const incidentCases = pgTable("incident_cases", { id: uuid("id").defaultRandom().primaryKey(), merchantId: uuid("merchant_id").notNull().references(() => merchants.id), incidentId: uuid("incident_id").notNull().references(() => incidents.id), caseId: uuid("case_id").notNull().references(() => recoveryCases.id), reason: text("reason").notNull(), ...timestamps }, (table) => ({ memberIdx: uniqueIndex("incident_cases_member_idx").on(table.incidentId, table.caseId) }));
export const proposals = pgTable("proposals", { id: uuid("id").defaultRandom().primaryKey(), merchantId: uuid("merchant_id").notNull().references(() => merchants.id), caseId: uuid("case_id").notNull().references(() => recoveryCases.id), obligationId: uuid("obligation_id").notNull().references(() => obligations.id), type: text("type").notNull(), intendedOutcome: text("intended_outcome").notNull(), recipient: text("recipient").notNull(), scope: text("scope").notNull(), channel: text("channel").notNull(), structuredPayload: jsonb("structured_payload").$type<Record<string, unknown>>().notNull(), evidenceIds: jsonb("evidence_ids").$type<string[]>().notNull(), uncertainty: text("uncertainty").notNull(), explanation: text("explanation").notNull(), policyResult: jsonb("policy_result").$type<Record<string, unknown>>().notNull(), requiresApproval: boolean("requires_approval").notNull(), status: text("status").notNull(), modelRunId: uuid("model_run_id"), actionVersion: integer("action_version").notNull(), ...timestamps });
export const approvals = pgTable("approvals", { id: uuid("id").defaultRandom().primaryKey(), merchantId: uuid("merchant_id").notNull().references(() => merchants.id), proposalId: uuid("proposal_id").notNull().references(() => proposals.id), requestedBy: text("requested_by").notNull(), decidedBy: text("decided_by"), decision: text("decision").notNull(), editedPayload: jsonb("edited_payload").$type<Record<string, unknown>>(), rationale: text("rationale"), decidedAt: timestamp("decided_at", { withTimezone: true }), ...timestamps });
export const policies = pgTable("policies", { id: uuid("id").defaultRandom().primaryKey(), merchantId: uuid("merchant_id").notNull().references(() => merchants.id), version: integer("version").notNull(), reviewFirst: boolean("review_first").notNull(), allowedChannels: jsonb("allowed_channels").$type<string[]>().notNull(), contactStartHour: integer("contact_start_hour").notNull(), contactEndHour: integer("contact_end_hour").notNull(), timezone: text("timezone").notNull(), maxAttempts: integer("max_attempts").notNull(), minimumSpacingHours: integer("minimum_spacing_hours").notNull(), discountsAllowed: boolean("discounts_allowed").notNull(), autoSendClasses: jsonb("auto_send_classes").$type<string[]>().notNull(), incidentSuppression: boolean("incident_suppression").notNull(), ...timestamps });
export const jobs = pgTable("jobs", { id: uuid("id").defaultRandom().primaryKey(), merchantId: uuid("merchant_id").notNull().references(() => merchants.id), kind: text("kind").notNull(), idempotencyKey: text("idempotency_key").notNull(), status: text("status").notNull(), caseId: uuid("case_id").references(() => recoveryCases.id), proposalId: uuid("proposal_id").references(() => proposals.id), batchRunId: uuid("batch_run_id"), runAfter: timestamp("run_after", { withTimezone: true }), attempts: integer("attempts").notNull().default(0), lastError: text("last_error"), ...timestamps }, (table) => ({ idempotencyIdx: uniqueIndex("jobs_merchant_idempotency_idx").on(table.merchantId, table.idempotencyKey) }));
export const ledgerEntries = pgTable("ledger_entries", { id: uuid("id").defaultRandom().primaryKey(), merchantId: uuid("merchant_id").notNull().references(() => merchants.id), obligationId: uuid("obligation_id").notNull().references(() => obligations.id), paymentId: uuid("payment_id").notNull().references(() => payments.id), amount: integer("amount").notNull(), currency: varchar("currency", { length: 3 }).notNull(), idempotencyKey: text("idempotency_key").notNull(), verifiedAt: timestamp("verified_at", { withTimezone: true }).notNull(), ...timestamps }, (table) => ({ idempotencyIdx: uniqueIndex("ledger_merchant_idempotency_idx").on(table.merchantId, table.idempotencyKey) }));
export const auditEvents = pgTable("audit_events", { id: uuid("id").defaultRandom().primaryKey(), merchantId: uuid("merchant_id").notNull().references(() => merchants.id), actor: actorType("actor").notNull(), eventType: text("event_type").notNull(), entityType: text("entity_type").notNull(), entityId: text("entity_id").notNull(), summary: text("summary").notNull(), beforeSummary: jsonb("before_summary").$type<Record<string, unknown>>(), afterSummary: jsonb("after_summary").$type<Record<string, unknown>>(), sourceIds: jsonb("source_ids").$type<string[]>().notNull(), provider: text("provider"), invocationReason: text("invocation_reason"), inputHash: text("input_hash"), usage: jsonb("usage").$type<Record<string, number>>(), ...{ createdAt: timestamps.createdAt } });
export const agentRuns = pgTable("agent_runs", { id: uuid("id").defaultRandom().primaryKey(), merchantId: uuid("merchant_id").notNull().references(() => merchants.id), caseId: uuid("case_id").notNull().references(() => recoveryCases.id), provider: text("provider").notNull(), model: text("model").notNull(), status: text("status").notNull(), stepCount: integer("step_count").notNull(), toolCallSummaries: jsonb("tool_call_summaries").$type<string[]>().notNull(), error: text("error"), invocationReason: text("invocation_reason"), inputHash: text("input_hash"), skipped: boolean("skipped").notNull().default(false), usage: jsonb("usage").$type<Record<string, number>>(), startedAt: timestamp("started_at", { withTimezone: true }).notNull(), finishedAt: timestamp("finished_at", { withTimezone: true }) });
export const connectorAccounts = pgTable("connector_accounts", { id: uuid("id").defaultRandom().primaryKey(), merchantId: uuid("merchant_id").notNull().references(() => merchants.id), type: text("type").notNull(), mode: text("mode").notNull(), status: text("status").notNull(), scopes: jsonb("scopes").$type<string[]>().notNull(), encryptedTokenRef: text("encrypted_token_ref"), lastSyncAt: timestamp("last_sync_at", { withTimezone: true }), ...timestamps });
export const webhookReceipts = pgTable("webhook_receipts", { id: uuid("id").defaultRandom().primaryKey(), merchantId: uuid("merchant_id").notNull().references(() => merchants.id), eventId: text("event_id").notNull(), rawBody: text("raw_body").notNull(), payloadHash: text("payload_hash").notNull(), eventType: text("event_type"), providerPaymentId: text("provider_payment_id"), providerLinkId: text("provider_link_id"), status: text("status").notNull(), receivedAt: timestamp("received_at", { withTimezone: true }).notNull(), appliedAt: timestamp("applied_at", { withTimezone: true }) }, (table) => ({ eventIdx: uniqueIndex("webhook_receipts_merchant_event_idx").on(table.merchantId, table.eventId) }));
export const merchantInstructions = pgTable("merchant_instructions", { id: uuid("id").defaultRandom().primaryKey(), merchantId: uuid("merchant_id").notNull().references(() => merchants.id), caseId: uuid("case_id").references(() => recoveryCases.id), instruction: text("instruction").notNull(), intent: text("intent").notNull(), status: text("status").notNull(), pauseUntil: timestamp("pause_until", { withTimezone: true }), batchRunId: uuid("batch_run_id"), createdAt: timestamp("created_at", { withTimezone: true }).notNull(), completedAt: timestamp("completed_at", { withTimezone: true }), error: text("error") });
export const batchRuns = pgTable("batch_runs", { id: uuid("id").defaultRandom().primaryKey(), merchantId: uuid("merchant_id").notNull().references(() => merchants.id), instructionId: uuid("instruction_id").notNull().references(() => merchantInstructions.id), instruction: text("instruction").notNull(), status: text("status").notNull(), concurrency: integer("concurrency").notNull(), caseIds: jsonb("case_ids").$type<string[]>().notNull(), completedCaseIds: jsonb("completed_case_ids").$type<string[]>().notNull(), failedCaseIds: jsonb("failed_case_ids").$type<string[]>().notNull(), startedAt: timestamp("started_at", { withTimezone: true }).notNull(), finishedAt: timestamp("finished_at", { withTimezone: true }), error: text("error") });
export const evaluationRuns = pgTable("evaluation_runs", { id: uuid("id").primaryKey(), datasetVersion: text("dataset_version").notNull(), buildId: text("build_id").notNull(), mode: appMode("mode").notNull(), provider: text("provider").notNull(), startedAt: timestamp("started_at", { withTimezone: true }).notNull(), finishedAt: timestamp("finished_at", { withTimezone: true }).notNull(), metrics: jsonb("metrics").$type<Record<string, unknown>>().notNull(), integrationProof: jsonb("integration_proof").$type<Record<string, unknown>>().notNull(), baseline: jsonb("baseline").$type<Record<string, unknown>>(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const evaluationResults = pgTable("evaluation_results", { id: uuid("id").defaultRandom().primaryKey(), runId: uuid("run_id").notNull().references(() => evaluationRuns.id), caseId: text("case_id").notNull(), expected: jsonb("expected").$type<Record<string, unknown>>().notNull(), actual: jsonb("actual").$type<Record<string, unknown>>().notNull(), status: text("status").notNull(), reason: text("reason"), startingOutstanding: integer("starting_outstanding").notNull(), remainingValue: integer("remaining_value").notNull() });
export const recoveryState = pgTable("recovery_state", { id: integer("id"), workspaceId: uuid("workspace_id").primaryKey(), merchantId: uuid("merchant_id").notNull(), payload: jsonb("payload").$type<DemoWorldPayload>().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() });

export type DemoWorldPayload = Record<string, unknown>;

export const schema = { merchants, customers, obligations, recoveryCases, signals, paymentAttempts, paymentLinks, payments, invoices, messages, documents, incidents, incidentCases, proposals, approvals, policies, jobs, ledgerEntries, auditEvents, agentRuns, connectorAccounts, webhookReceipts, merchantInstructions, batchRuns, evaluationRuns, evaluationResults, recoveryState };
